name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Hanya jalankan pipeline saat ada perubahan di branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Simpan username Docker Hub di Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Simpan password Docker Hub di Secrets

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/your-image-name:latest

      # Optional: Logout from Docker Hub
      - name: Logout from Docker Hub
        run: docker logout
